version: 2
updates:
  - package-ecosystem: npm
    schedule:
      interval: weekly
      day: monday
      time: "14:20"
      timezone: America/Denver
    directories:
      - "/"
    groups:
      npm:
        patterns:
          - "*"
