version: 2
updates:
  - package-ecosystem: npm
    schedule:
      interval: "daily"
      time: "16:41"
      timezone: "America/Denver"
    directory: "/"
    groups:
      npm:
        patterns:
          - "*"
